export const LOAD_APP = 'LOAD_APP'
export const LOAD_APP_FULFILLED = 'LOAD_APP_FULFILLED'
export const LOAD_APP_REJECTED = 'LOAD_APP_REJECTED'

export const GET_DEVICES = 'GET_DEVICES'
export const GET_DEVICES_FULFILLED = 'GET_DEVICES_FULFILLED'
export const GET_DEVICES_REJECTED = 'GET_DEVICES_REJECTED'
