export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_LOGOUT_FULFILLED = 'AUTH_LOGOUT_FULFILLED'
export const AUTH_LOGOUT_REJECTED = 'AUTH_LOGOUT_REJECTED'

export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGIN_FULFILLED = 'AUTH_LOGIN_FULFILLED'
export const AUTH_LOGIN_REJECTED = 'AUTH_LOGIN_REJECTED'

export const AUTH_PASSWORD_CONFIRMATION = 'AUTH_PASSWORD_CONFIRMATION'
export const AUTH_PASSWORD_CONFIRMATION_FULFILLED = 'AUTH_PASSWORD_CONFIRMATION_FULFILLED'
export const AUTH_PASSWORD_CONFIRMATION_REJECTED = 'AUTH_PASSWORD_CONFIRMATION_REJECTED'

export const AUTH_RECOVER_PASSWORD = 'AUTH_RECOVER_PASSWORD'
export const AUTH_RECOVER_PASSWORD_FULFILLED = 'AUTH_RECOVER_PASSWORD_FULFILLED'
export const AUTH_RECOVER_PASSWORD_REJECTED = 'AUTH_PASSWORAUTH_RECOVER_PASSWORD_REJECTEDD_CONFIRMATION_REJECTED'
